### ISSUE TITLE
SSL certificate problem: self-signed certificate in certificate chain

### ISSUE THREAD

**Issue by rossaddison** [rossaddison/invoice#44]
### What do you get instead? The above error with the following trace:

Http\Client\Exception\RequestException: SSL certificate problem: self-signed certificate in certificate chain in C:\wamp128\www\invoice\vendor\php-http\curl-client\src\Client.php:166
Stack trace:
#0 C:\wamp128\www\invoice\vendor\vjik\telegram-bot-api\src\Client\PsrTelegramClient.php(34): Http\Client\Curl\Client->sendRequest(Object(HttpSoft\Message\Request))
#1 C:\wamp128\www\invoice\vendor\vjik\telegram-bot-api\src\TelegramBotApi.php(248): Vjik\TelegramBot\Api\Client\PsrTelegramClient->send(Object(Vjik\TelegramBot\Api\Method\Update\SetWebhook))
#2 C:\wamp128\www\invoice\vendor\vjik\telegram-bot-api\src\TelegramBotApi.php(2383): Vjik\TelegramBot\Api\TelegramBotApi->send(Object(Vjik\TelegramBot\Api\Method\Update\SetWebhook))
#3 C:\wamp128\www\invoice\src\Invoice\Helpers\Telegram\TelegramHelper.php(77): Vjik\TelegramBot\Api\TelegramBotApi->setWebhook('http://invoice....', NULL, NULL, NULL, NULL, NULL)
#4 C:\wamp128\www\invoice\src\Invoice\Telegram\TelegramController.php(102): App\Invoice\Helpers\Telegram\TelegramHelper->setWebhook(Object(Yiisoft\Router\FastRoute\UrlGenerator), NULL, NULL, NULL, NULL, NULL)
#5 [internal function]: App\Invoice\Telegram\TelegramController->index(Object(HttpSoft\Message\ServerRequest), Object(Yiisoft\Router\FastRoute\UrlGenerator), Object(App\Handler\NotFoundHandler))
#6 C:\wamp128\www\invoice\vendor\yiisoft\injector\src\Injector.php(86): ReflectionFunction->invokeArgs(Array)
#7 C:\wamp128\www\invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareFactory.php(271): Yiisoft\Injector\Injector->invoke(Object(Closure), Array)
#8 C:\wamp128\www\invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(93): Psr\Http\Server\MiddlewareInterface@anonymous->process(Object(HttpSoft\Message\ServerRequest), Object(App\Handler\NotFoundHandler))
#9 C:\wamp128\www\invoice\vendor\yiisoft\auth\src\Middleware\Authentication.php(58): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#10 C:\wamp128\www\invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(93): Yiisoft\Auth\Middleware\Authentication->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#11 C:\wamp128\www\invoice\src\Middleware\AccessChecker.php(36): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#12 C:\wamp128\www\invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareFactory.php(216): App\Middleware\AccessChecker->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#13 C:\wamp128\www\invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(93): Psr\Http\Server\MiddlewareInterface@anonymous->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#14 C:\wamp128\www\invoice\vendor\yiisoft\data-response\src\Middleware\FormatDataResponse.php(27): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#15 C:\wamp128\www\invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(93): Yiisoft\DataResponse\Middleware\FormatDataResponse->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#16 C:\wamp128\www\invoice\vendor\yiisoft\csrf\src\CsrfMiddleware.php(48): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#17 C:\wamp128\www\invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(93): Yiisoft\Csrf\CsrfMiddleware->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#18 C:\wamp128\www\invoice\vendor\yiisoft\yii-debug-viewer\src\Middleware\ToolbarMiddleware.php(71): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#19 C:\wamp128\www\invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(93): Yiisoft\Yii\Debug\Viewer\Middleware\ToolbarMiddleware->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#20 C:\wamp128\www\invoice\vendor\yiisoft\yii-debug-api\src\Debug\Middleware\DebugHeaders.php(26): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#21 C:\wamp128\www\invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(93): Yiisoft\Yii\Debug\Api\Debug\Middleware\DebugHeaders->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#22 C:\wamp128\www\invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(49): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#23 C:\wamp128\www\invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareDispatcher.php(48): Yiisoft\Middleware\Dispatcher\MiddlewareStack->handle(Object(HttpSoft\Message\ServerRequest))
#24 C:\wamp128\www\invoice\vendor\yiisoft\router\src\MatchingResult.php(112): Yiisoft\Middleware\Dispatcher\MiddlewareDispatcher->dispatch(Object(HttpSoft\Message\ServerRequest), Object(App\Handler\NotFoundHandler))
#25 C:\wamp128\www\invoice\vendor\yiisoft\router\src\Middleware\Router.php(59): Yiisoft\Router\MatchingResult->process(Object(HttpSoft\Message\ServerRequest), Object(App\Handler\NotFoundHandler))
#26 C:\wamp128\www\invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(93): Yiisoft\Router\Middleware\Router->process(Object(HttpSoft\Message\ServerRequest), Object(App\Handler\NotFoundHandler))
#27 C:\wamp128\www\invoice\vendor\yiisoft\yii-middleware\src\Locale.php(111): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#28 C:\wamp128\www\invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(93): Yiisoft\Yii\Middleware\Locale->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#29 C:\wamp128\www\invoice\vendor\yiisoft\user\src\Login\Cookie\CookieLoginMiddleware.php(71): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#30 C:\wamp128\www\invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(93): Yiisoft\User\Login\Cookie\CookieLoginMiddleware->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#31 C:\wamp128\www\invoice\vendor\yiisoft\cookies\src\CookieMiddleware.php(84): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#32 C:\wamp128\www\invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(93): Yiisoft\Cookies\CookieMiddleware->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#33 C:\wamp128\www\invoice\vendor\yiisoft\csrf\src\CsrfMiddleware.php(48): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#34 C:\wamp128\www\invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(93): Yiisoft\Csrf\CsrfMiddleware->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#35 C:\wamp128\www\invoice\vendor\yiisoft\session\src\SessionMiddleware.php(33): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#36 C:\wamp128\www\invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(93): Yiisoft\Session\SessionMiddleware->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#37 C:\wamp128\www\invoice\vendor\yiisoft\yii-sentry\src\SentryMiddleware.php(27): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#38 C:\wamp128\www\invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(93): Yiisoft\Yii\Sentry\SentryMiddleware->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#39 C:\wamp128\www\invoice\vendor\yiisoft\error-handler\src\Middleware\ErrorCatcher.php(133): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#40 C:\wamp128\www\invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(93): Yiisoft\ErrorHandler\Middleware\ErrorCatcher->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#41 C:\wamp128\www\invoice\vendor\yiisoft\request-provider\src\RequestCatcherMiddleware.php(29): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#42 C:\wamp128\www\invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(93): Yiisoft\RequestProvider\RequestCatcherMiddleware->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#43 C:\wamp128\www\invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(49): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#44 C:\wamp128\www\invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareDispatcher.php(48): Yiisoft\Middleware\Dispatcher\MiddlewareStack->handle(Object(HttpSoft\Message\ServerRequest))
#45 C:\wamp128\www\invoice\vendor\yiisoft\yii-debug-api\src\Debug\Middleware\MiddlewareDispatcherMiddleware.php(22): Yiisoft\Middleware\Dispatcher\MiddlewareDispatcher->dispatch(Object(HttpSoft\Message\ServerRequest), Object(App\Handler\NotFoundHandler))
#46 C:\wamp128\www\invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(93): Yiisoft\Yii\Debug\Api\Debug\Middleware\MiddlewareDispatcherMiddleware->process(Object(HttpSoft\Message\ServerRequest), Object(App\Handler\NotFoundHandler))
#47 C:\wamp128\www\invoice\vendor\yiisoft\yii-debug-viewer\src\Middleware\ToolbarMiddleware.php(71): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#48 C:\wamp128\www\invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(93): Yiisoft\Yii\Debug\Viewer\Middleware\ToolbarMiddleware->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#49 C:\wamp128\www\invoice\vendor\yiisoft\yii-debug-api\src\Debug\Middleware\DebugHeaders.php(26): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#50 C:\wamp128\www\invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(93): Yiisoft\Yii\Debug\Api\Debug\Middleware\DebugHeaders->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#51 C:\wamp128\www\invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(49): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#52 C:\wamp128\www\invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareDispatcher.php(48): Yiisoft\Middleware\Dispatcher\MiddlewareStack->handle(Object(HttpSoft\Message\ServerRequest))
#53 C:\wamp128\www\invoice\vendor\yiisoft\yii-http\src\Application.php(77): Yiisoft\Middleware\Dispatcher\MiddlewareDispatcher->dispatch(Object(HttpSoft\Message\ServerRequest), Object(App\Handler\NotFoundHandler))
#54 C:\wamp128\www\invoice\vendor\yiisoft\yii-runner-http\src\HttpApplicationRunner.php(159): Yiisoft\Yii\Http\Application->handle(Object(HttpSoft\Message\ServerRequest))
#55 C:\wamp128\www\invoice\public\index.php(43): Yiisoft\Yii\Runner\Http\HttpApplicationRunner->run()
#56 {main}

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      | 
| Operating system |

**Comment by rossaddison** [comment]
I have tested the package through the test site yii3i.co.uk and did not have any issues. I currently have ssl certificate issues with regards to composer update where my antivirus is interfering so I suspect this is a local issue.
